let myJokes = [
  {
    category: "Programming",
    type: "single",
    joke: "How do you tell HTML from HTML5?\n- Try it out in Internet Explorer\n- Did it work?\n- No?\n- It's HTML5.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 43,
    safe: true,
    lang: "en",
  },
  {
    category: "Pun",
    type: "single",
    joke: "Oysters hate to give away their pearls because they are shellfish.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 90,
    safe: true,
    lang: "en",
  },
  {
    category: "Dark",
    type: "twopart",
    setup: "What do Ted Bundy and the Space Shuttle Columbia have in common?",
    delivery: "They both left bodies in four states.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: true,
    },
    id: 154,
    safe: false,
    lang: "en",
  },
  {
    category: "Pun",
    type: "single",
    joke: "To whoever stole my copy of Microsoft Office, I will find you. You have my Word!",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 191,
    safe: true,
    lang: "en",
  },
  {
    category: "Misc",
    type: "twopart",
    setup: "I like my girls how I like my COVID.",
    delivery: "19 and easily spread.",
    flags: {
      nsfw: true,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: true,
    },
    id: 167,
    safe: false,
    lang: "en",
  },
  {
    category: "Pun",
    type: "twopart",
    setup:
      "To prove he was right, the flat-earther walked to the end of the Earth.",
    delivery: "He eventually came around.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    safe: true,
    id: 280,
    lang: "en",
  },
  {
    category: "Pun",
    type: "twopart",
    setup:
      'Mickey Mouse and Minnie Mouse are in the divorce court.\n"Mickey", the judge says, "I\'m sorry. I can\'t grant you a divorce on the grounds of insanity. Minnie seems quite sane to me."',
    delivery:
      '"I didn\'t say she was insane", exclaims Mickey.\n"I said she was fucking Goofy."',
    flags: {
      nsfw: true,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: true,
    },
    id: 225,
    safe: false,
    lang: "en",
  },
  {
    category: "Pun",
    type: "twopart",
    setup: "Which part of the hospital has the least privacy?",
    delivery: "The ICU.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    safe: true,
    id: 285,
    lang: "en",
  },
  {
    category: "Dark",
    type: "twopart",
    setup: "Everyone says that Hitler really loved animals.",
    delivery: "Then why did he kill 6 million of them?",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: true,
      sexist: false,
      explicit: true,
    },
    id: 106,
    safe: false,
    lang: "en",
  },
  {
    category: "Dark",
    type: "twopart",
    setup: "Dads are like boomerangs.",
    delivery: "I hope.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 166,
    safe: true,
    lang: "en",
  },

  {
    category: "Dark",
    type: "twopart",
    setup: "Say what you want about pedophiles...",
    delivery: "But at least they drive slowly through the school zones.",
    flags: {
      nsfw: true,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: true,
    },
    id: 161,
    safe: false,
    lang: "en",
  },
  {
    category: "Misc",
    type: "single",
    joke: "Two reasons I don't give money to homeless people.\n1) They are going to spend it all on drugs and alcohol\n2) I am going to spend it all on drugs and alcohol.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 72,
    safe: false,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: "Your mama's so FAT she can't save files bigger than 4GB.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: true,
    },
    id: 9,
    safe: false,
    lang: "en",
  },
  {
    category: "Misc",
    type: "single",
    joke: "My husband and I were happy for 20 years. And then we met.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    safe: true,
    id: 273,
    lang: "en",
  },
  {
    category: "Dark",
    type: "twopart",
    setup: "Life's like my dick.",
    delivery: "The more children you have, the harder it gets.",
    flags: {
      nsfw: true,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: true,
    },
    id: 107,
    safe: false,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: "Algorithm: A word used by programmers when they don't want to explain how their code works.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 51,
    safe: true,
    lang: "en",
  },
  {
    category: "Misc",
    type: "single",
    joke: "My wife and I have reached the difficult decision that we do not want children.\nIf anybody does, please just send me your contact details and we can drop them off tomorrow.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 257,
    safe: true,
    lang: "en",
  },
  {
    category: "Dark",
    type: "twopart",
    setup: "What's the difference between Jesus and a hooker?",
    delivery: "The look on their face when you are nailing them.",
    flags: {
      nsfw: false,
      religious: true,
      political: false,
      racist: false,
      sexist: false,
      explicit: true,
    },
    safe: false,
    id: 261,
    lang: "en",
  },
  {
    category: "Pun",
    type: "twopart",
    setup: "What do Asian people call fingers?",
    delivery: "Limb Limbs.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: true,
      sexist: false,
      explicit: false,
    },
    id: 95,
    safe: false,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: "The glass is neither half-full nor half-empty, the glass is twice as big as it needs to be.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 23,
    safe: true,
    lang: "en",
  },
];

let getJoke = document.querySelector("#getJoke");
getJoke.addEventListener('click',()=>{
    let randomIndex = Math.ceil(Math.random() * myJokes.length - 1);
    let randomJokes = myJokes[randomIndex].joke || myJokes[randomIndex].setup;
    let cardText = document.querySelector(".card-text");
    cardText.textContent = randomJokes;
})


